[features]
seeds = false
skip-lint = false
[programs.localnet]
escrow1 = "EGGJvpjms73Mcm5FBVuuctBdRqJnzXouSxBgvSLwy6A1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/erika/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
